# Generated by Django 4.2.1 on 2023-06-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_event_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='restrictions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Party', 'Party'), ('Game', 'Game'), ('Club', 'Club'), ('House Party', 'House Party'), ('Bar', 'Bar')], default='Party', max_length=100),
        ),
    ]
