# Generated by Django 4.2.1 on 2023-06-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_event_notes_alter_event_restrictions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
