# Generated by Django 4.2.1 on 2023-06-09 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_event_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='zipcode',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999), django.core.validators.RegexValidator('^\\d{5}$', 'Enter a valid 5-digit zipcode.')]),
        ),
    ]
