# Generated by Django 4.2.1 on 2023-06-09 00:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_event_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='zipcode',
            field=models.CharField(default=0, max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$')]),
        ),
    ]
