# Generated by Django 4.2.1 on 2023-06-09 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_event_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='zipcode',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid zipcode.', regex='^\\d{5}(?:-\\d{4})?$')]),
        ),
    ]
